plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "config/initializers/filter_parameter_logging.rb"

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
